import { storage } from './StorageService.js';
import { logger } from './Logger.js';

const log = logger.create('HomeLayoutManager');

/**
 * Manages the layout configuration for the Home page, including ordering
 * and visibility of different sections (Continue Watching, Next Up, Libraries).
 *
 * Persists the configuration to localStorage.
 */
class HomeLayoutManager {
    constructor() {
        this.STORAGE_KEY = 'pref:homeLayout';
    }

    /**
     * Gets the current saved layout from storage.
     * @returns {Array<{id: string, title: string, hidden: boolean, order: number}>|null}
     */
    getSavedLayout() {
        const saved = storage.getItem(this.STORAGE_KEY);
        if (!saved) return null;
        try {
            return JSON.parse(saved);
        } catch (e) {
            log.error('Failed to parse saved home layout', e);
            return null;
        }
    }

    /**
     * Saves a new layout configuration to storage.
     * @param {Array<{id: string, title: string, hidden: boolean, order: number}>} layout
     */
    saveLayout(layout) {
        // Ensure order matches array index before saving
        layout.forEach((item, index) => {
            item.order = index;
        });
        storage.setItem(this.STORAGE_KEY, JSON.stringify(layout));
        log.info('Home layout saved successfully.');
    }

    /**
     * Applies the current layout configuration to an array of raw RowDescriptors.
     * Takes the server-provided descriptors, filters hidden ones, and sorts
     * them according to the user's saved preferences.
     *
     * Items that exist in descriptors but NOT in the saved layout (e.g. newly added libraries)
     * are appended to the end of the list automatically.
     *
     * @param {Array<Object>} descriptors - The raw row descriptors from HomePage.
     * @returns {Array<Object>} - The filtered and sorted descriptors ready for rendering.
     */
    applyLayout(descriptors) {
        const savedLayout = this.getSavedLayout();

        // If there is no saved layout, simply return the descriptors as generated by the page,
        // but perhaps filtered by global legacy settings (like pref:hideMyMedia).
        if (!savedLayout || savedLayout.length === 0) {
            // Respect legacy hide setting if no layout config exists
            if (storage.getItem('pref:hideMyMedia') === 'true') {
                return descriptors.filter((d) => d.id !== 'my-media');
            }
            return descriptors;
        }

        const layoutMap = new Map();
        savedLayout.forEach((item) => {
            layoutMap.set(item.id, item);
        });

        // First pass: Filter and attach order value
        // Process descriptors to map saved user preferences (hiding and custom sorting order).
        const processedDescriptors = [];
        const newDescriptors = []; // Descriptors without a saved preference

        // Loop through all raw descriptors provided by the home screen logic
        // and map them against user's custom layout settings.
        for (const desc of descriptors) {
            const config = layoutMap.get(desc.id);

            if (config) {
                // Skip if hidden
                // Skip rendering if the section has been toggled to hidden by the user.
                if (config.hidden) continue;

                // Keep the descriptor but augment with user sort order
                // Attach the user-defined order for subsequent sorting.
                processedDescriptors.push({
                    ...desc,
                    _userOrder: config.order
                });
            } else {
                // New library or section not in preferences yet!
                // We'll append it to the end.
                // If a section is new (e.g. newly created server library), we default it to visible
                // and place it at the end of the screen.
                newDescriptors.push(desc);
            }
        }

        // Sort processed descriptors by user order
        // Order sections sequentially based on user's layout preferences.
        processedDescriptors.sort((a, b) => a._userOrder - b._userOrder);

        // Map them back to clean descriptors and append new ones
        // Remove the temporary ordering metadata before returning clean descriptor data.
        const finalDescriptors = processedDescriptors.map((pd) => {
            const clean = { ...pd };
            delete clean._userOrder;
            return clean;
        });

        // Combine the sorted existing layout rows with any new/appended sections.
        return [...finalDescriptors, ...newDescriptors];
    }

    /**
     * Generates a syncable layout array by combining the saved preferences
     * with the current live descriptors (handling renamed items or new items).
     * This is used by the Settings UI to display the full list of manageable rows.
     *
     * @param {Array<Object>} descriptors - The raw row descriptors from HomePage/API.
     * @returns {Array<{id: string, title: string, hidden: boolean, order: number}>}
     */
    buildSettingsLayout(descriptors) {
        const savedLayout = this.getSavedLayout() || [];
        const savedMap = new Map(savedLayout.map((item) => [item.id, item]));

        const settingsList = [];
        let nextOrder = 0;

        // 1. Add known saved items in their saved order, updating titles if they changed
        savedLayout.forEach((item) => {
            // Verify this descriptor still exists (maybe library was deleted from server)
            const liveDesc = descriptors.find((d) => d.id === item.id);
            if (liveDesc) {
                settingsList.push({
                    id: liveDesc.id,
                    title: liveDesc.title, // Use live title in case it was renamed on server
                    hidden: item.hidden || false,
                    order: nextOrder++
                });
            }
        });

        // 2. Append new items that aren't in the saved layout yet
        descriptors.forEach((desc) => {
            if (!savedMap.has(desc.id)) {
                // Handle legacy transition for 'My Media'
                const isHidden = desc.id === 'my-media' && storage.getItem('pref:hideMyMedia') === 'true';

                settingsList.push({
                    id: desc.id,
                    title: desc.title,
                    hidden: isHidden,
                    order: nextOrder++
                });
            }
        });

        // Ensure order values are sequential and correct after any manipulation
        // Sequence layout items sequentially according to their final array positions.
        settingsList.forEach((item, index) => {
            item.order = index;
        });

        return settingsList;
    }
}

export const homeLayoutManager = new HomeLayoutManager();
